# Generated by Django 5.2.15 on 2026-06-17 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('rules', models.TextField(blank=True, help_text='Entry/exit rules for this strategy')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('position_size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven')], max_length=10)),
                ('rr_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('planned_rr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('trade_date', models.DateField()),
                ('trade_time', models.TimeField(blank=True, null=True)),
                ('session', models.CharField(choices=[('asia', 'Asia'), ('london', 'London'), ('new_york', 'New York'), ('overlap', 'Overlap'), ('other', 'Other')], default='other', max_length=20)),
                ('timeframe', models.CharField(blank=True, help_text='Primary timeframe e.g. 15m, 1H', max_length=20)),
                ('timeframe_confluences', models.JSONField(blank=True, default=list)),
                ('confluences', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('emotional_state', models.CharField(blank=True, max_length=100)),
                ('mistakes', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='journal.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('mime_type', models.CharField(default='image/jpeg', max_length=50)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journal.trade')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
